### ISSUE TITLE
Call not written to GAbbI file

### ISSUE THREAD

**Issue by kd7uiy** [kd7uiy/trusted-qsl#3]
This causes the output of the file to look strange on LOTW. Fix this!

**Comment by Boggartfly** [comment]
Hi,
I'm interested to build this further, I want to build an Android app with this library. Can you guide me in some way? I have a vague idea on how to do it.
Regards
Parth V Sane

**Comment by kd7uiy** [comment]
This library works with Android, and in fact it is what I made it for. I use it in my app HamFinder. If you take a look at the example in the demo folder, you can see the start of how this might be done. What I did for my app was to store QSOs in a database, and parse through the information to populate the table as appropriate. See https://github.com/kd7uiy/trusted-qsl/blob/master/demo/src/WriteGabbiTest.java for that code. 

Basically, you extend WriteGabbi, and implement a function called GetStations() that returns all of the possible stations, and getQsoData(Station station) that returns all of the Qsos for that station call. It is written so you can have multiple stations at a time. Ham Finder automatically fills in the station information, so it's easy for that app, other applications will have to decide how they want to handle filling in the station information. There is also a function "publishProgress" which is called periodically to allow the program to update the status of producing the Qso file. 

Also, you have to get the P12 certificate file to the device. That is the hardest part of making this happen. See the main routine for what to do once you get the P12 certificate to the device. I don't know of any way at the moment short of getting it from the host computer. The certificate is created on the host computer, and never passed to LOTW, so it only resides in Tqsl. Let me know if you find a better way to do this, I'd love to include it in this library!
